version: '3.4'

services:
  agriapp2023:
    image: agriapp2023
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
      - 22:22
      - 3000:3000
